### ISSUE TITLE
copy_reg ?  Error

### ISSUE THREAD

**Issue by s1162276945** [cartopy/ConvMF#2]
Traceback (most recent call last):
===================================ConvMF Option Setting===================================
  File "D:/pycode/ConvMF/run.py", line 132, in <module>
    R, D_all = data_factory.load(aux_path)
	data path - D:/pycode/ConvMF/data/preprocessed/movielens_10m/cf/0.2_1/
  File "D:\pycode\ConvMF\data_manager.py", line 31, in load
	aux path - D:/pycode/ConvMF/data/preprocessed/movielens_10m/
    R = pickle.load(open(path + "ratings.all", "rb"))  # , encoding='iso-8859-
ImportError: No module named 'copy_reg\r'

**Comment by s1162276945** [comment]
hope somebody can deal with it
