### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by s1162276945** [cartopy/ConvMF#3]
When I set 
------------------------------------
do_preprocess = True
----------------------------
Traceback (most recent call last):
  File "D:/pycode/ConvMF/run.py", line 97, in <module>
    path_rating, path_itemtext, min_rating, max_length, max_df, vocab_size)
  File "D:\pycode\ConvMF\data_manager.py", line 372, in preprocess
    tmp_plot = tmp[1].split('|')
IndexError: list index out of range
---------------------------------------------------------------------
do_preprocess = False
----------------------------------------------------------
Traceback (most recent call last):
  File "D:/pycode/ConvMF/run.py", line 132, in <module>
    R, D_all = data_factory.load(aux_path)
  File "D:\pycode\ConvMF\data_manager.py", line 42, in load
    R = pickle.load(open(path + "ratings.all", "rb"))
  File "D:\Anaconda2\lib\pickle.py", line 1384, in load
===================================ConvMF Option Setting===================================
    return Unpickler(file).load()
  File "D:\Anaconda2\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "D:\Anaconda2\lib\pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "D:\Anaconda2\lib\pickle.py", line 1130, in find_class
    __import__(module)
ImportError: No module named copy_get
----------------------------------------------------------------------------how could it be?

**Comment by aierlansea** [comment]
use linux system run，version  python 2.7，keras 0.3.3，theano 0.8.1 ,cuda 8.0 cudnn 4.0,welcom discussion 18165275595@163.com

**Comment by zanshuxun** [comment]
there is no  tmp[1] because one of your items has no description,
